tfpytests manifest fix
tensorflow/ngraph-bridge pull request #652
Opened 2020-09-04 21:46 UTC by bani-intelaipg

2020-09-04 23:14 UTC, adk9 requested changes

2020-09-04 23:14 UTC, adk9 commented on test/python/tensorflow/tf_unittest_runner.py
>      for aTestCaseID in alltests:
Can you please follow the style here: https://google.github.io/styleguide/pyguide.html?

2020-09-04 23:14 UTC, adk9 commented on test/python/tensorflow/tf_unittest_runner.py
> +
Use "sets" for tests and you can simply take a set difference for this. You'll also be able to eliminate any duplicated tests as a result of using sets.

2020-09-04 23:15 UTC, bani-intelaipg commented on test/python/tensorflow/tf_unittest_runner.py
> +            regex_pattern = '^' + regex_input + '$'
This was buggy earlier.

2020-09-05 16:32 UTC, adk9 approved these changes
Looks good, thanks.

2020-09-05 16:34 UTC, merged