Add NMSV2 translation
tensorflow/ngraph-bridge pull request #740
Opened 2020-12-09 07:37 UTC by kanvi-nervana

2020-12-09 19:25 UTC, adk9 requested changes

2020-12-09 22:59 UTC, kanvi-nervana commented on test/python/test_nms.py
> +            nmsv4 = tf.image.non_max_suppression(
This commit got in accidentally, along with the WIP commit. I will push the updated test.

2020-12-09 23:03 UTC, kanvi-nervana commented on ngraph_bridge/ngraph_builder.cc
> +                                   ng_unused1, ng_unused2));
These are required otherwise there's an error
**InvalidArgumentError: "NonMaxSuppressionV2" requires 2 input(s), got 4 instead**

2020-12-10 00:06 UTC, adk9 commented on ngraph_bridge/ngraph_builder.cc
> +                                   ng_unused1, ng_unused2));
Yes, looks like it's needed. We should remove this requirement in the future.

2020-12-10 00:08 UTC, adk9 commented on ngraph_bridge/ngraph_builder.cc
> +      op->name(), ng_scores_unsqueezed1, ng_axis_scores);
There are two Unsqueezes being used going from 1D to 3D.

2020-12-10 01:01 UTC, adk9 approved these changes

2020-12-10 03:45 UTC, merged