build options
tensorflow/ngraph-bridge pull request #783
Opened 2021-01-15 21:25 UTC by kanvi-nervana

Build options: use ov from location and prebuit tf cannot be used together because of ABI issues

2021-01-20 17:49 UTC, adk9 requested changes
Why can't one use prebuilt-tensorflow with OV built with _GLIBCXX_USE_CXX11_ABI=0? Perhaps we should default to building everything with _GLIBCXX_USE_CXX11_ABI=0?

2021-01-20 22:41 UTC, kanvi-nervana commented
> Why can't one use prebuilt-tensorflow with OV built with _GLIBCXX_USE_CXX11_ABI=0? Perhaps we should default to building everything with _GLIBCXX_USE_CXX11_ABI=0?

You could, you would need to make sure that when you use these 2 options together then you provide the right location of OV built with ABI=0
Fixing the build to use ABI=0 always is a better option.

2021-01-22 01:24 UTC, adk9 approved these changes

2021-01-22 08:00 UTC, bani-intelaipg commented on build_ngtf.py
>      # this is set to 1
This comment should be updated?

2021-01-22 08:02 UTC, bani-intelaipg approved these changes

2021-01-22 17:38 UTC, kanvi-nervana commented on build_ngtf.py
>      # this is set to 1
It is comment in general

2021-01-22 18:22 UTC, merged